# Generated by Django 4.0 on 2022-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_profile_delete_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lft',
            field=models.BooleanField(default=False),
        ),
    ]
