# Generated by Django 4.0 on 2022-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_profile_birthday_profile_lfc_profile_lft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
