# Generated by Django 4.0 on 2022-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0005_profile_buddies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lfc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lft',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
