# Generated by Django 4.0 on 2022-03-15 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teams', '0002_team_city_team_country_alter_team_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='recruting',
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(default=None, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
